# Generated by Django 5.2.5 on 2025-09-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameraaccessrequest',
            name='requested_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cameraaccessrequest',
            name='requested_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
